Jump with animation
SourceGold/SourceGold-Dev pull request #13
Opened 2023-03-20 14:52 UTC by DKevi

Implement jump with animation;
Create a script for animation controller;

2023-03-20 21:25 UTC, jialuogao requested changes
LGTM, commented on some minor questions.
Also wonder where did those hooks file go? 
For LFS could you add that to .gitignore?
Thanks

2023-03-20 21:25 UTC, jialuogao commented on Assets/Scenes/SampleScene.unity
> +  jumpPower: 0
is this intended to have a 0 value? If yes just wondering how this value gets assigned?

2023-03-20 21:25 UTC, jialuogao commented on Assets/Blink/Art/Characters/LowPoly/Demo_FREE_LowPolyCharacter/LowPolyHumanAnimator.controller
Do we want to remove all these? If not we might want to add it back?

2023-03-20 21:29 UTC, zyd2001 commented
> LGTM, commented on some minor questions. Also wonder where did those hooks file go? For LFS could you add that to .gitignore? Thanks

Those files should not be there if LFS is configured correctly, so it is no need to modify .gitignore

2023-03-20 21:33 UTC, DKevi commented on Assets/Scenes/SampleScene.unity
> +  jumpPower: 0
They can be set to any value. The higher the jump power the higher the character will jump. 0 means no jump at all. It should have a field somewhere you can change easily while using the UI.

2023-03-20 21:47 UTC, AlstonXiao commented
LGTM. Remember these unity description file (like scene.unity) is not really human readable. Make sure you resolve them in local before push and pull request. (1, merge dev to your branch. 2, resolve conflict. 3, push and pull request)

2023-03-21 04:31 UTC, jialuogao commented on Assets/Scenes/SampleScene.unity
> +  jumpPower: 0
Ok, just wondering if we want a default value but not needed to modify in this PR

2023-03-21 04:31 UTC, jialuogao commented
Ok, will unblock and approve

2023-03-21 04:31 UTC, jialuogao approved these changes, later dismissed

2023-03-21 13:59 UTC, zyd2001 commented
我试了一下，好像跳的过程中按空格也会触发下一次跳跃，应该算是bug吧

2023-03-21 14:16 UTC, jialuogao commented
> 我试了一下，好像跳的过程中按空格也会触发下一次跳跃，应该算是bug吧

这不是isgrounded的检测吗？难道有bug，会不会因为跳的时候坐标没动，所以检测还在地上？ @DKevi 看一下吧

2023-03-21 15:06 UTC, johnw08 commented
> 我试了一下，好像跳的过程中按空格也会触发下一次跳跃，应该算是bug吧

这会不会是他设计的多段跳

2023-03-23 01:21 UTC, DKevi commented
我这看貌似没啥问题...? @zyd2001 你设的参数多少，我复现一下
@johnw08 并没有多段跳呢还

2023-03-23 03:24 UTC, zyd2001 commented
> 我这看貌似没啥问题...? @zyd2001 你设的参数多少，我复现一下 @johnw08 并没有多段跳呢还

我就是直接checkout到你的branch运行的，我试试看弄个新的clone

2023-03-23 03:50 UTC, DKevi commented
> > 我这看貌似没啥问题...? @zyd2001 你设的参数多少，我复现一下 @johnw08 并没有多段跳呢还
> 
> 我就是直接checkout到你的branch运行的，我试试看弄个新的clone

我和诺神研究了一下，是跳的太低了动画没结束但是人其实已经落地了，就会有这样的效果

2023-03-25 21:23 UTC, jialuogao approved these changes

2023-03-25 21:23 UTC, merged