Yw
SourceGold/SourceGold-Dev pull request #14
Opened 2023-03-26 00:26 UTC by johnw08

Added animation for movement and combat. Attack during movement will stop the movement.

Combat key:
J: light attack
K: heavy attack
U: left punch
I: right punch
B: buff

2023-03-26 04:23 UTC, jialuogao commented
Please update the PR name so that it is meaningful instead of "Yw"

2023-03-26 04:30 UTC, johnw08 commented
> Please update the PR name so that it is meaningful instead of "Yw"

Done it.

2023-04-01 20:35 UTC, DKevi approved these changes, later dismissed
LGTM

2023-04-01 20:48 UTC, jialuogao commented on Assets/Character Script/BasicCombat.cs
> +using System.Collections;
如果不需要就删掉吧

2023-04-01 20:48 UTC, jialuogao commented on Assets/Character Script/BasicCombat.cs.meta
> +fileFormatVersion: 2
如果不需要就删掉吧

2023-04-01 20:48 UTC, jialuogao commented on Assets/Character Script/BasicMoving.cs
> +        _direction_temp = _direction;
有用吗？

2023-04-01 20:52 UTC, jialuogao requested changes
minor

2023-04-01 20:52 UTC, jialuogao commented on Assets/Character Script/BasicMoving.cs
> +        //if (anim.GetCurrentAnimatorStateInfo(0))
没用的删掉吧

2023-04-01 21:47 UTC, jialuogao approved these changes

2023-04-01 21:48 UTC, merged