[Backend] Update stats and add inventory basic
SourceGold/SourceGold-Dev pull request #38
Opened 2023-08-13 08:25 UTC by jialuogao

2023-08-20 05:38 UTC, AlstonXiao requested changes
Some naming change suggested

2023-08-20 05:38 UTC, AlstonXiao commented on Assets/Script/Backend/GameObject/GameObject.cs
> +            ParentName = parentName;
Why we need a parent here.

2023-08-20 05:38 UTC, AlstonXiao commented on Assets/Script/Backend/GameStages/GameSceneTest.cs
> +            AddGameObject(new Enemy(enemyName, LoadEnemyStats(enemyName), LoadDefaultEnvironmentalStats(isEnemy: true)));
Same

2023-08-20 05:38 UTC, AlstonXiao commented on Assets/Script/Backend/GameObject/HittableObject.cs
> +        public virtual void UpdateHitPoint(int changeInHp)
Hitpoint会和3d上面的hit的位置产生歧义。考虑一下能不能换个名字？

2023-08-20 09:13 UTC, jialuogao commented on Assets/Script/Backend/GameObject/HittableObject.cs
> +        public virtual void UpdateHitPoint(int changeInHp)
但HP就是hitpoint，我改一下gothit的名字吧

2023-08-20 09:14 UTC, jialuogao commented on Assets/Script/Backend/GameObject/GameObject.cs
> +            ParentName = parentName;
parent是用来trigger on death event的，其实比起问，更简单的办法是你搜一下那里用到了
if (!IsAlive)
{
    EventManager.TriggerEvent(GameEventTypes.GetObjectOnDeathEvent(ParentName));
}

2023-08-20 09:21 UTC, jialuogao commented on Assets/Script/Backend/GameObject/HittableObject.cs
> +        public virtual void UpdateHitPoint(int changeInHp)
gothit 改成 gotdamaged了

2023-08-20 09:23 UTC, jialuogao commented on Assets/Script/Backend/GameStages/GameSceneTest.cs
> +            AddGameObject(new Enemy(enemyName, LoadEnemyStats(enemyName), LoadDefaultEnvironmentalStats(isEnemy: true)));
是问parent吗？如果是那在另一个thread里聊

2023-08-20 09:25 UTC, jialuogao commented on Assets/Script/Backend/GameObject/HittableObject.cs
> +        public virtual void UpdateHitPoint(int changeInHp)
你有其他地方需要这个命名吗？stats.hitpoint难道不能很完整的表达这个hitpoint是hp的意思吗？

2023-08-20 19:06 UTC, AlstonXiao commented on Assets/Script/Backend/GameObject/HittableObject.cs
> +        public virtual void UpdateHitPoint(int changeInHp)
因为hitpoint还可以表达hit的3d位置。到时候我们debug武器的时候可能会用到，比如检测剑和人物在哪里被攻击到了。虽然我知道hp就是hitpoint的缩写，但考虑到hitpoint确实可以表达其他意思能不能改成health point

2023-08-20 19:07 UTC, AlstonXiao commented on Assets/Script/Backend/GameObject/GameObject.cs
> +            ParentName = parentName;
我觉得parent会很怪，因为parent一般指继承hierarchy的parent而这里其实是game object？感觉可以考虑换一个名字。

2023-08-27 04:43 UTC, AlstonXiao approved these changes

2023-08-27 04:43 UTC, jialuogao commented on Assets/Script/Backend/GameObject/HittableObject.cs
> +        public virtual void UpdateHitPoint(int changeInHp)
经讨论 沿用HitPoint

2023-08-27 04:43 UTC, merged